# Generated by Django 5.2.4 on 2025-07-18 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='races.racetrack')),
            ],
        ),
    ]
