# Generated by Django 5.2.4 on 2025-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_alter_grandprix_options_raceresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racetrack',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
