# Generated by Django 5.2.4 on 2025-07-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_alter_grandprix_date_alter_racetrack_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grandprix',
            unique_together={('track', 'date')},
        ),
    ]
