# Generated by Django 5.2.4 on 2025-08-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_alter_racetrack_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandprix',
            old_name='track',
            new_name='race_track',
        ),
        migrations.AlterUniqueTogether(
            name='grandprix',
            unique_together={('race_track', 'date')},
        ),
    ]
