# Generated by Django 5.2.4 on 2025-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driver_name'),
        ('races', '0010_remove_raceresult_unique_driver_per_grand_prix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('grand_prix', 'finish_position'), ('grand_prix', 'start_position')},
        ),
        migrations.AddConstraint(
            model_name='raceresult',
            constraint=models.UniqueConstraint(fields=('grand_prix', 'driver'), name='unique_driver_per_grand_prix'),
        ),
    ]
