# Generated by Django 5.2.4 on 2025-07-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_rename_team_id_index_driver_id_index_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Constructor',
        ),
        migrations.RenameIndex(
            model_name='constructor',
            new_name='constructor_id_index',
            old_name='team_id_index',
        ),
    ]
