# Generated by Django 5.2.4 on 2025-07-18 18:47

import drivers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('short_name', models.CharField(max_length=3, validators=[drivers.models.validate_exactly_3_chars])),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='id_index')],
            },
        ),
    ]
