# Generated by Django 5.2.4 on 2025-07-18 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='team_id_index',
            old_name='id_index',
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
