# Generated by Django 5.2.4 on 2025-07-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_team_rename_id_index_team_id_index_team_id_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driver',
            new_name='driver_id_index',
            old_name='team_id_index',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='team_id_index',
            old_name='id_index',
        ),
    ]
