# Generated by Django 5.2.4 on 2025-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_rename_team_constructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
