# Generated by Django 5.2.4 on 2025-08-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
