# Generated by Django 5.2.4 on 2025-07-18 21:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_rename_team_constructor_and_more'),
        ('races', '0002_grandprix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grandprix',
            options={'verbose_name': 'Grand prix', 'verbose_name_plural': 'Grand prix'},
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('finish_position', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('finish_status', models.CharField(choices=[('finished', 'Finished the race'), ('retired', 'Did not finish the race for whatever reason'), ('mechanical', 'Mechanical failure')], default='finished', max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('is_sprint', models.BooleanField(default=False)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='drivers.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='drivers.driver')),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='races.grandprix')),
            ],
            options={
                'ordering': ['grand_prix', 'finish_position'],
                'constraints': [models.UniqueConstraint(fields=('grand_prix', 'driver'), name='unique_driver_per_grand_prix')],
                'unique_together': {('grand_prix', 'finish_position'), ('grand_prix', 'start_position')},
            },
        ),
    ]
