# Generated by Django 5.2.4 on 2025-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_alter_grandprix_date_alter_racetrack_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='racetrack',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
