# Generated by Django 5.2.4 on 2025-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_alter_grandprix_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
