# Generated by Django 5.2.4 on 2025-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_alter_grandprix_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetrack',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
