# Generated by Django 5.2.4 on 2025-08-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_rename_track_grandprix_race_track_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raceresult',
            name='unique_driver_per_grand_prix',
        ),
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='racetrack',
            unique_together={('name', 'country')},
        ),
    ]
