# Generated by Django 5.2.4 on 2025-08-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_alter_raceresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='is_sprint',
        ),
        migrations.AddField(
            model_name='grandprix',
            name='is_sprint',
            field=models.BooleanField(default=False),
        ),
    ]
