# Generated by Django 5.2.4 on 2025-08-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_remove_raceresult_is_sprint_grandprix_is_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='finish_status',
            field=models.CharField(choices=[('Finished', 'Finished the race'), ('Lapped', 'Finished at least one lap behind'), ('Retired', 'Did not finish the race for whatever reason'), ('Mechanical', 'Mechanical failure')], default='finished', max_length=100),
        ),
    ]
