# Generated by Django 5.2.4 on 2025-08-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_alter_raceresult_finish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='grandprix',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
