# Generated by Django 5.2.4 on 2025-08-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_grandprix_name_grandprix_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
