# Generated by Django 5.2.4 on 2025-08-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_alter_raceresult_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('grand_prix', 'finish_position')},
        ),
    ]
