# Generated by Django 5.2.4 on 2025-08-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0016_alter_raceresult_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grandprix',
            unique_together={('race_track', 'date', 'is_sprint')},
        ),
    ]
